Lesson1
Mihail-tec/webix-start pull request #2
Opened 2022-04-05 13:53 UTC by Mihail-tec

2022-04-05 14:21 UTC, AlexeyXB requested changes

2022-04-05 14:21 UTC, AlexeyXB commented on index.js
> +        css: { background: "#d6d2d2" },
Лучше сделать css, куда добавить backround

2022-04-05 14:21 UTC, AlexeyXB commented on style.css
> +.webix_clean .webix_template {
Вместо этого можно добавить autoheight для templates

2022-04-05 14:21 UTC, AlexeyXB commented on index.js
> +            type: "section",
Лишний type: "section"

2022-04-05 14:21 UTC, AlexeyXB commented on index.js
> +                id: "mylist",
Пока что тебе нет нужды использовать id для элементов

2022-04-05 19:04 UTC, HelgaListopad requested changes

2022-04-05 19:04 UTC, HelgaListopad commented on index.html
> +    <link rel="stylesheet" type="text/css" href="../webix/codebase/webix.css">
Код всё-таки должен работать
И либо вебикс берётся с [CDN](https://cdn.webix.com/edge/webix.js) (`.css` там под тем же именем), либо JS и CSS должны быть добавлены в проект (GPL версия скачивается [здесь](https://github.com/webix-hub/webix) или на [сайте](https://webix.com/get-webix-gpl/))

2022-04-05 19:04 UTC, HelgaListopad commented on index.js
> +        autoheight: true,
Не поддерживается layout'ом

2022-04-05 19:04 UTC, HelgaListopad commented on style.css
> +    background-color: #d6d2d2;
Остаётся ещё border-color у строк в листе (попробуй выставить ему transparent, чтобы не зависел напрямую от цвета фона)
Если глянуть в инспекторе, то нужный класс - `.webix_list_item`

2022-04-05 19:04 UTC, HelgaListopad commented on index.js
> +        height: 850,
Сразу же после `autoheight` стоит `height`. Оба нужно удалить.)
В этом случае фиксированная высота не подходит, так как UI уже не подстроится под размер браузера.
Если вьюшки внутри сжимают layout под свой размер (как и происходит, если убрать эту высоту), значит, где-то не хватает spacer'a

2022-04-05 19:04 UTC, HelgaListopad commented on index.js
> +        width: 200,
Это layout, который занимает всю ширину страницы и внутри готорого находятся другие вьюшки. Ограничение ширины до 200 здесь
- не подходит
- не сработает (на body ширина будет 100% - это фича такой инициализации)

2022-04-05 19:04 UTC, HelgaListopad commented on index.js
> +          {
Ширину этой части ("меню" с листом и темплейтом) лучше уменьшить и сделать фиксированной

2022-04-05 19:04 UTC, HelgaListopad commented on index.js
> +              },
Это то самое место, где не хватает spacer'a.
Как и говорилось на лекции, такая форма принимает фиксированную высоту элементов внутри, а потом тянет за собой весь parent layout.

2022-04-05 19:04 UTC, HelgaListopad commented on index.js
> +                css: "text_decor",
Здесь получается очень большой темплейт для маленького текста. 
Ты можешь выставить темплейту `autoheight` и оставить только выравнивание текста по центру. При этом высота темплейта подстроится под высоту текста, а лист (у которого не указана высота) займёт оставшееся доступное место.

2022-04-06 08:14 UTC, Mihail-tec commented
> Таким образом ты переопределяешь стиль для всех webix ui.list. Лучше такой стиль добавить только для необходимого листа, т.е. для тех, на кого рассчитаны классы

2022-04-06 08:37 UTC, AlexeyXB approved these changes

2022-04-06 09:49 UTC, HelgaListopad approved these changes

2022-04-06 09:49 UTC, merged