lesson 2: added validate, popup, send data from fields in table
Mihail-tec/webix-start pull request #3
Opened 2022-04-06 14:10 UTC by Mihail-tec

I separated popup and functions so that only rendering is in that file

2022-04-06 14:20 UTC, AlexeyXB requested changes

2022-04-06 14:20 UTC, AlexeyXB commented on function.js
> +  var validate = $$("form").validate();
1) Тут нет необходимости в создании переменной `validate`, т.к. ты ее потом используешь только один раз для проверки валидности данных
2) Для чего ты тут используешь `var`? Я думаю лучше в данной ситуации использование `const`.

2022-04-06 14:20 UTC, AlexeyXB commented on index.js
> +                if (webix.rules.isNumber(value)) {
Если хочешь использовать функцию, то можно просто вернуть` return webix.rules.isNumber(value)`. 
Но в данном случае, можно просто `rating: webix.rules.isNumber`.

2022-04-06 20:49 UTC, HelgaListopad requested changes

2022-04-06 20:49 UTC, HelgaListopad commented on index.js
> +            template: "#title# #year# #rating# #votes#",
Для таблицы неактуально, нужно удалить.
Template для данных выставляется отдельно для каждой колонки в таблице (сейчас это происходит автоматически из-за `autoConfig`)

2022-04-06 20:49 UTC, HelgaListopad commented on popup.js
> +webix.ready(function () {
Мне не нравится, что вызовы `webix.ui` разнесены по разным файлам.
Лучше было бы
- хранить в popup.js объект с конфигурацией окна,
- подключать его в index.js,
- в index.js инитить сначала popup, потом основной UI страницы (так на момент создания кнопки уже будет popup с указанным ID)
```js
webix.ui( popupConfig );
webix.ui( mainUI );
```

2022-04-06 20:49 UTC, HelgaListopad commented on function.js
> +    webix.message("success added");
Выводить лучше более верный текст: например, "Successfully added"

2022-04-06 20:49 UTC, HelgaListopad commented on popup.js
> +          webix.message("you touch " + id);
`"Click on " + id`

2022-04-07 07:35 UTC, AlexeyXB approved these changes

2022-04-07 09:57 UTC, HelgaListopad approved these changes

2022-04-07 09:57 UTC, merged