lesson 3: added multiview, added new features to the table, added use…
Mihail-tec/webix-start pull request #4
Opened 2022-04-07 15:00 UTC by Mihail-tec

…r section, added products section

2022-04-07 20:02 UTC, AlexeyXB requested changes

2022-04-07 20:02 UTC, AlexeyXB commented on datatable.js
> +      {id:"votes", header:"votes", sort:"int", width: 100},
Не хватает фильтрации у `votes`.
Также сортировка работает неверно.

2022-04-07 20:02 UTC, AlexeyXB commented on datatable.js
> +      {id:"rank", header:"Rank", width:"80", css:"rank" },
Судя по скриншоту в задании первая колонка не должна иметь значение в `header`

2022-04-07 20:02 UTC, AlexeyXB commented on datatable.js
> +      { template:"<span class='webix_icon wxi-trash delete_icon'></span>", width:"30"},
Ширину лучше увеличить, чтобы не было наслоения иконки и скролла.
<img width="656" alt="Снимок экрана 2022-04-07 в 22 26 10" src="https://user-images.githubusercontent.com/82041711/162281407-7924f3ac-1839-4f0f-b777-3b7c1fca7581.png">

2022-04-07 20:02 UTC, AlexeyXB commented on form.js
> +            value: "add new",
`Value` кнопки не всегда соответсвует действию. Когда ты добавляешь новое - `value` должно быть`Add new`. Когда меняешь существующую запись -`Save`

2022-04-07 20:02 UTC, AlexeyXB commented on index.js
> +              {id:"users",  rows:[listUser, ]},
Для `users` получается структура `rows:[rows[]]`. Лучше в таком случае что-то вроде  `{id:"users",  ...listUser},`

2022-04-07 20:02 UTC, AlexeyXB commented on listUser.js
> +        webix_icon(e, id) {
Не лучшая идея использовать `webix_icon` в качестве названия функции. Лучше в данном случае `wxi-close` или даже добавить в `span` новый класс `remove`

2022-04-07 20:02 UTC, AlexeyXB commented on products.js
> +  view: "treetable",
По заданию нужно, чтобы в `treetable` выбиралась ячейка, а не строка.

2022-04-07 20:02 UTC, AlexeyXB commented on style.css
>  .text_decor {
1) Для центрирования template в `text_decor` достаточно добавить `text-align: center;`
2) Для иконок, которые нужно разместить справа, можно добавить новый класс - `right_position` и прописать в нем `float: right`. В том виде как у тебя сейчас - ты переопределяешь расположение для всех иконок.

2022-04-08 09:39 UTC, AlexeyXB approved these changes

2022-04-08 10:11 UTC, HelgaListopad requested changes

2022-04-08 10:11 UTC, HelgaListopad commented on datatable.js
> +      { template:"<span class='webix_icon wxi-trash delete_icon'></span>", width:"80"},
Ширина должна задаваться числом

2022-04-08 10:11 UTC, HelgaListopad commented on datatable.js
> +          const values = $$("datatable").getItem(id);
`$$` можно заменить на `this`, раз функция не стрелочная

2022-04-08 10:11 UTC, HelgaListopad commented on function.js
>    if ($$("form").validate()) {
У тебя есть переменная `form` - лучше использовать её

2022-04-08 10:11 UTC, HelgaListopad commented on function.js
> +  const save = $$("save");
`save` не используется в этой функции

2022-04-08 10:11 UTC, HelgaListopad commented on listUser.js
> +                const value = $$("list_input").getValue().toLowerCase();
Контекст позволяет использовать `this` вмвесто `$$`  - это и понятнее, и немного короче

2022-04-08 10:11 UTC, HelgaListopad commented on products.js
> +    { id: "price", header: "Price", width: 200 },
Вместо фиксированной ширины выставь этой колонке `fillspace: true`, чтобы отрисовать строки до правого края таблицы

2022-04-08 11:05 UTC, HelgaListopad approved these changes

2022-04-08 11:05 UTC, merged